import { empty } from "rxjs";

export const RoutersLink = {
    pedestrianEntranceUpdate:"pedestrianEntranceUpdate/",
    integratedVehicleUpdate:"integratedVehicleUpdate/",
    accessPointRecordUpdate:"accessPointRecordUpdate/",
    pedestrianEntranceUsers:"pedestrianEntranceUsers/",
    accessPointUpdate:"accessPointUpdate/",
    gettotaldataDelete:"deleteRegisterEvent/",
    gettotaldatagallery:"gettotaldatagallery/",
    gettotaldata:"gettotaldata/",
    closingMinuteDetail:"/home/closingMinute/closingMinuteDetail/",
    initialRegistrationReady:"initialRegistrationReady/",
    assistantDetail:"home/listRecordsMade/assistantList/assistantDetail/",
    assistant:"home/listRecordsMade/assistantList/",
    purchaseOperatorsDetail:"home/purchaseOperators/purchaseOperatorsDetail/",
    register: "register",
    indexClosingMinute:"indexClosingMinute",
    closingMinute:"closingMinute",
    closingMinuteAdmin:"closingMinuteAdmin",
    logBooks:"logBooks",
    logBooksAdmin:"logBooksAdmin",
    editUsers:"editUsers",
    updateUsersClient:"updateUsersClient",
    indexgetgoin:"listUsers/",
    registerUpdate: "registerUpdate",
    accessPointRecord:"accessPointRecord",
    imgUpdate:"imgUpdate",
    registerChallenge:"registerChallenge",
    registerExpoAllies: "registerExpoAllies",
    passwordUpdate:"passwordUpdate",
    home:"/home/dashboard",
    content:"home/content",
    profile:"home/profile",
    login:"pages/login/",
    loginClients:"pages/loginClient/",
    loginApi:"login",
    forgotPassword:"forgotPassword/",
    city:"city",
    category:"category",
    status:"status/",
    getUsersData:"getUsersData/",
    benefits:"benefits",
    scale:"scale",
    challenges:"challenges",
    menu:"menu/",
    gettotal:"gettotal?id=",
    createEventosGetfinal:"create_eventos_getfinal?idClientsProjects=",
    getEvent:"proyects",
    getEventList:"proyects",
    listCustomer:"listCustomer/",
    listUsers:"listUsers/",
    getEventListPost:"institutionHeadquarters",
    getEventPost:"proyects",
    getEventImg:"listRegisterImageEventsList?idClientsProjects=",
    deleteRegisterImageEvent:"deleteRegisterImageEvent/",
    resgisterImageEvents:"resgisterImageEvents",
    assignUserAudit:"list/log_users/",
    assignUserAuditReady:"list/log_users",
    assignUserAuditPost:"list/log_users",
    operator:"operator/",
    operatorPost:"operator",
    customerDetail:"customerDetail/",
    customerDetailPost:"customerDetail",
    office:"office",
    officeGet:"office/",
    registeredVehicle:"registeredVehicle",
    registeredVehicleGet: "getRegisteredVehicle/",
    getIntegratedVehicle:"getIntegratedVehicle/",
    integratedVehicle:"integratedVehicle",
    getIntegratedVehicleFull:"integratedVehicle/",
    accessPoint:"accessPoint",
    accessPointGet:"accessPoint/",
    customerCompany:"customerCompany",
    customerCompanyGet:"customerCompany/",
    customerCompanyUpdate:"customerCompanyUpdate/",
    clientUsers:"clientUsers",
    clientUsersGet:"getClientUsers/",
    pedestrianEntranceDetail:"pedestrianEntranceDetail/",
    pedestrianEntrance:"pedestrianEntrance",
    pedestrianEntranceGet:"pedestrianEntrance/"
};

export const Menssage = {
    color:"El color es obligatorio",
    title:"El titulo es obligatorio",
    imgLogo:"El logo es obligatorio",
    nameOperators:"",
    companyIdentity:"",
    idinstitutionHeadquarters:"",
    idusersuper:"",
    name:"El Nombre es obligatorio",
    surname:"",
    passwordVerifi:"",
    description:"",
    idrol:"",
    daneCorregimiento:"",
    corregimiento:"",
    daneSedeInstitutions:"",
    sedeInstitutions:"",
    idEducationalInstitutions:"",
    zode:"El zode es obligatorio",
    daneMunicipality:"El No. de DANE del municipio es Obligatorio",
    municipality:"El nombre del municipio es obligatorio",
    daneInstitutions:"El No. de DANE de la institución es Obligatorio",
    institutions:"El nombre de la institución es obligatorio",
    rector:"El nombre del rector es obligatorio",
    telephone:"El No. de teléfono es obligatorio",
    direction:"La dirección es obligatoria",
    idusers:"El intentificador de usuario es obligatorio",
    idProyectsClients:"El identificador de proyecto es obligatorio",
    idImg:"No haz agregado una imagen",
    idEvents:"No haz seleccionado un evento",
    nameEvents:"softsaenz",
    nameEventsNull:"No hay datos que descargar",
    passwordAES:"Softsaenz2023*",
    error:"Error",
    token:"token",
    userDenied:"El Usuario administrador no puede hacer cierre de minuta",
    customerDetail:"customerDetail",
    acccess:"acccess",
    menu:"menu",
    server:"En la conexión del servidor",
    serverNull:"No puedes iniciar sesión sin escoger tu punto de ingreso",
    userValid:"El correo ya se encuentra registrado",
    emailValid:"El Email ingresado no se encuentra registrado",
    businessName: "La razón social es obligatoria",
    identificationCard: "El numero de identificación es obligatorio",
    idCategoryToRegister: "La categoria es obligatoria",
    address: "La dirección es obligatoria",
    phone: "El teléfono es obligatorio",
    idCity: "La ciudad es obligatoria",
    email: "El Correo es obligatorio",
    nit: "El nit no es valido",
    empty: "",
    valiEmail: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$',
    validNumber: /^[1-9]\d{6,10}$/,
    success: "Usuario registrado correctamente",
    successUpdate: "Usuario actualizado correctamente",
    successDelete: "Registro eliminado correctamente",
    successForgot: "Ha tu correo registrado enviamos un link para la recuperación de la contraseña",
    exito:"Exito",
    password: "La contraseña es obligatoria",
    updatePassword: "La contraseña y el correo fueron actualizado correctamente",
    habeas: false,
    habeasDataText:"Debes aceptar las política​ de habeas data",
    personalDataPolicy:"Debes acpetar los términos y condiciones",
    monthlyBudget:"El presupuesto mensual es obligatorio",
    contactPerson:"La persona de contacto es obligatorio",
    successExpo: "El registrado se ralizó correctamente",
    idRolAdmin: 1,
    idRolAdminClientsVigilant: 3,
    idRolAdminClients: 2,
};